package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private String idCliente;
	private Pais pais;
	private TipoDocumento tipoDocumento;
	private String idNacionalidad;
	private String idTipoDeDocumento;
	private String nombres;
	private String apellidoMaterno;
	private String apellidoPaterno;
	private String idTipoCliente;
	private Long idDestinatario;
	private String idGiro;
	private String razonSocial;
	private Set ubicacionClientes = new HashSet(0);
	private Set biometrias = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(String idCliente, Pais pais, TipoDocumento tipoDocumento, String idNacionalidad,
			String idTipoDeDocumento, String nombres, String apellidoMaterno, String apellidoPaterno,
			String idTipoCliente, Long idDestinatario, String idGiro, String razonSocial, Set ubicacionClientes,
			Set biometrias) {
		this.idCliente = idCliente;
		this.pais = pais;
		this.tipoDocumento = tipoDocumento;
		this.idNacionalidad = idNacionalidad;
		this.idTipoDeDocumento = idTipoDeDocumento;
		this.nombres = nombres;
		this.apellidoMaterno = apellidoMaterno;
		this.apellidoPaterno = apellidoPaterno;
		this.idTipoCliente = idTipoCliente;
		this.idDestinatario = idDestinatario;
		this.idGiro = idGiro;
		this.razonSocial = razonSocial;
		this.ubicacionClientes = ubicacionClientes;
		this.biometrias = biometrias;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(String idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	public String getIdTipoDeDocumento() {
		return this.idTipoDeDocumento;
	}

	public void setIdTipoDeDocumento(String idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getIdTipoCliente() {
		return this.idTipoCliente;
	}

	public void setIdTipoCliente(String idTipoCliente) {
		this.idTipoCliente = idTipoCliente;
	}

	public Long getIdDestinatario() {
		return this.idDestinatario;
	}

	public void setIdDestinatario(Long idDestinatario) {
		this.idDestinatario = idDestinatario;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public Set getUbicacionClientes() {
		return this.ubicacionClientes;
	}

	public void setUbicacionClientes(Set ubicacionClientes) {
		this.ubicacionClientes = ubicacionClientes;
	}

	public Set getBiometrias() {
		return this.biometrias;
	}

	public void setBiometrias(Set biometrias) {
		this.biometrias = biometrias;
	}

}
