package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * DespachadorGiros generated by hbm2java
 */
public class DespachadorGiros implements java.io.Serializable {

	private long idDespachadorGiros;
	private Date horaRecepGiro;
	private Date fechaRecepGiro;
	private Long idGiro;
	private String comisionGiro;
	private String valorGiro;
	private Long idSuRed;
	private String idMatrixGirosYServicios;
	private String idEfectivoLtda;
	private String idServientrega;
	private String idEfecty;
	private String idSuperGiros;
	private String idMovilRed;
	private String idInvercosta;
	private String idCoopetran;
	private String idGirosAlInstanteSin;
	private Long idBancoAvvillas;
	private Long idDespachador;

	public DespachadorGiros() {
	}

	public DespachadorGiros(long idDespachadorGiros) {
		this.idDespachadorGiros = idDespachadorGiros;
	}

	public DespachadorGiros(long idDespachadorGiros, Date horaRecepGiro, Date fechaRecepGiro, Long idGiro,
			String comisionGiro, String valorGiro, Long idSuRed, String idMatrixGirosYServicios, String idEfectivoLtda,
			String idServientrega, String idEfecty, String idSuperGiros, String idMovilRed, String idInvercosta,
			String idCoopetran, String idGirosAlInstanteSin, Long idBancoAvvillas, Long idDespachador) {
		this.idDespachadorGiros = idDespachadorGiros;
		this.horaRecepGiro = horaRecepGiro;
		this.fechaRecepGiro = fechaRecepGiro;
		this.idGiro = idGiro;
		this.comisionGiro = comisionGiro;
		this.valorGiro = valorGiro;
		this.idSuRed = idSuRed;
		this.idMatrixGirosYServicios = idMatrixGirosYServicios;
		this.idEfectivoLtda = idEfectivoLtda;
		this.idServientrega = idServientrega;
		this.idEfecty = idEfecty;
		this.idSuperGiros = idSuperGiros;
		this.idMovilRed = idMovilRed;
		this.idInvercosta = idInvercosta;
		this.idCoopetran = idCoopetran;
		this.idGirosAlInstanteSin = idGirosAlInstanteSin;
		this.idBancoAvvillas = idBancoAvvillas;
		this.idDespachador = idDespachador;
	}

	public long getIdDespachadorGiros() {
		return this.idDespachadorGiros;
	}

	public void setIdDespachadorGiros(long idDespachadorGiros) {
		this.idDespachadorGiros = idDespachadorGiros;
	}

	public Date getHoraRecepGiro() {
		return this.horaRecepGiro;
	}

	public void setHoraRecepGiro(Date horaRecepGiro) {
		this.horaRecepGiro = horaRecepGiro;
	}

	public Date getFechaRecepGiro() {
		return this.fechaRecepGiro;
	}

	public void setFechaRecepGiro(Date fechaRecepGiro) {
		this.fechaRecepGiro = fechaRecepGiro;
	}

	public Long getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(Long idGiro) {
		this.idGiro = idGiro;
	}

	public String getComisionGiro() {
		return this.comisionGiro;
	}

	public void setComisionGiro(String comisionGiro) {
		this.comisionGiro = comisionGiro;
	}

	public String getValorGiro() {
		return this.valorGiro;
	}

	public void setValorGiro(String valorGiro) {
		this.valorGiro = valorGiro;
	}

	public Long getIdSuRed() {
		return this.idSuRed;
	}

	public void setIdSuRed(Long idSuRed) {
		this.idSuRed = idSuRed;
	}

	public String getIdMatrixGirosYServicios() {
		return this.idMatrixGirosYServicios;
	}

	public void setIdMatrixGirosYServicios(String idMatrixGirosYServicios) {
		this.idMatrixGirosYServicios = idMatrixGirosYServicios;
	}

	public String getIdEfectivoLtda() {
		return this.idEfectivoLtda;
	}

	public void setIdEfectivoLtda(String idEfectivoLtda) {
		this.idEfectivoLtda = idEfectivoLtda;
	}

	public String getIdServientrega() {
		return this.idServientrega;
	}

	public void setIdServientrega(String idServientrega) {
		this.idServientrega = idServientrega;
	}

	public String getIdEfecty() {
		return this.idEfecty;
	}

	public void setIdEfecty(String idEfecty) {
		this.idEfecty = idEfecty;
	}

	public String getIdSuperGiros() {
		return this.idSuperGiros;
	}

	public void setIdSuperGiros(String idSuperGiros) {
		this.idSuperGiros = idSuperGiros;
	}

	public String getIdMovilRed() {
		return this.idMovilRed;
	}

	public void setIdMovilRed(String idMovilRed) {
		this.idMovilRed = idMovilRed;
	}

	public String getIdInvercosta() {
		return this.idInvercosta;
	}

	public void setIdInvercosta(String idInvercosta) {
		this.idInvercosta = idInvercosta;
	}

	public String getIdCoopetran() {
		return this.idCoopetran;
	}

	public void setIdCoopetran(String idCoopetran) {
		this.idCoopetran = idCoopetran;
	}

	public String getIdGirosAlInstanteSin() {
		return this.idGirosAlInstanteSin;
	}

	public void setIdGirosAlInstanteSin(String idGirosAlInstanteSin) {
		this.idGirosAlInstanteSin = idGirosAlInstanteSin;
	}

	public Long getIdBancoAvvillas() {
		return this.idBancoAvvillas;
	}

	public void setIdBancoAvvillas(Long idBancoAvvillas) {
		this.idBancoAvvillas = idBancoAvvillas;
	}

	public Long getIdDespachador() {
		return this.idDespachador;
	}

	public void setIdDespachador(Long idDespachador) {
		this.idDespachador = idDespachador;
	}

}
