package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String idEmpleado;
	private String nombre;
	private String idGiros;
	private String tipoDocumento;
	private Long numDocumentoEmp;
	private Set giroses = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Empleado(String idEmpleado, String nombre, String idGiros, String tipoDocumento, Long numDocumentoEmp,
			Set giroses) {
		this.idEmpleado = idEmpleado;
		this.nombre = nombre;
		this.idGiros = idGiros;
		this.tipoDocumento = tipoDocumento;
		this.numDocumentoEmp = numDocumentoEmp;
		this.giroses = giroses;
	}

	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIdGiros() {
		return this.idGiros;
	}

	public void setIdGiros(String idGiros) {
		this.idGiros = idGiros;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Long getNumDocumentoEmp() {
		return this.numDocumentoEmp;
	}

	public void setNumDocumentoEmp(Long numDocumentoEmp) {
		this.numDocumentoEmp = numDocumentoEmp;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

}
