package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * FormaPagoEstatica generated by hbm2java
 */
public class FormaPagoEstatica implements java.io.Serializable {

	private String idFormaDePago;
	private Long cuentaAhorros;
	private Long tarjetaCredito;
	private Boolean cheque;
	private Boolean efectivo;
	private Set giroses = new HashSet(0);

	public FormaPagoEstatica() {
	}

	public FormaPagoEstatica(String idFormaDePago) {
		this.idFormaDePago = idFormaDePago;
	}

	public FormaPagoEstatica(String idFormaDePago, Long cuentaAhorros, Long tarjetaCredito, Boolean cheque,
			Boolean efectivo, Set giroses) {
		this.idFormaDePago = idFormaDePago;
		this.cuentaAhorros = cuentaAhorros;
		this.tarjetaCredito = tarjetaCredito;
		this.cheque = cheque;
		this.efectivo = efectivo;
		this.giroses = giroses;
	}

	public String getIdFormaDePago() {
		return this.idFormaDePago;
	}

	public void setIdFormaDePago(String idFormaDePago) {
		this.idFormaDePago = idFormaDePago;
	}

	public Long getCuentaAhorros() {
		return this.cuentaAhorros;
	}

	public void setCuentaAhorros(Long cuentaAhorros) {
		this.cuentaAhorros = cuentaAhorros;
	}

	public Long getTarjetaCredito() {
		return this.tarjetaCredito;
	}

	public void setTarjetaCredito(Long tarjetaCredito) {
		this.tarjetaCredito = tarjetaCredito;
	}

	public Boolean getCheque() {
		return this.cheque;
	}

	public void setCheque(Boolean cheque) {
		this.cheque = cheque;
	}

	public Boolean getEfectivo() {
		return this.efectivo;
	}

	public void setEfectivo(Boolean efectivo) {
		this.efectivo = efectivo;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

}
