package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Giros generated by hbm2java
 */
public class Giros implements java.io.Serializable {

	private String idGiros;
	private Empleado empleado;
	private FormaPagoEstatica formaPagoEstatica;
	private LocutorioSedeEspana locutorioSedeEspana;
	private String idCliente;
	private String idOrigen;
	private Date fechaGiro;
	private Double costoGiro;
	private String idDestino;
	private String idPais;
	private String idAdministrador;
	private String idVerificarMontoPermitido;
	private String idVerficarMonto;

	public Giros() {
	}

	public Giros(String idGiros) {
		this.idGiros = idGiros;
	}

	public Giros(String idGiros, Empleado empleado, FormaPagoEstatica formaPagoEstatica,
			LocutorioSedeEspana locutorioSedeEspana, String idCliente, String idOrigen, Date fechaGiro,
			Double costoGiro, String idDestino, String idPais, String idAdministrador, String idVerificarMontoPermitido,
			String idVerficarMonto) {
		this.idGiros = idGiros;
		this.empleado = empleado;
		this.formaPagoEstatica = formaPagoEstatica;
		this.locutorioSedeEspana = locutorioSedeEspana;
		this.idCliente = idCliente;
		this.idOrigen = idOrigen;
		this.fechaGiro = fechaGiro;
		this.costoGiro = costoGiro;
		this.idDestino = idDestino;
		this.idPais = idPais;
		this.idAdministrador = idAdministrador;
		this.idVerificarMontoPermitido = idVerificarMontoPermitido;
		this.idVerficarMonto = idVerficarMonto;
	}

	public String getIdGiros() {
		return this.idGiros;
	}

	public void setIdGiros(String idGiros) {
		this.idGiros = idGiros;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public FormaPagoEstatica getFormaPagoEstatica() {
		return this.formaPagoEstatica;
	}

	public void setFormaPagoEstatica(FormaPagoEstatica formaPagoEstatica) {
		this.formaPagoEstatica = formaPagoEstatica;
	}

	public LocutorioSedeEspana getLocutorioSedeEspana() {
		return this.locutorioSedeEspana;
	}

	public void setLocutorioSedeEspana(LocutorioSedeEspana locutorioSedeEspana) {
		this.locutorioSedeEspana = locutorioSedeEspana;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public String getIdOrigen() {
		return this.idOrigen;
	}

	public void setIdOrigen(String idOrigen) {
		this.idOrigen = idOrigen;
	}

	public Date getFechaGiro() {
		return this.fechaGiro;
	}

	public void setFechaGiro(Date fechaGiro) {
		this.fechaGiro = fechaGiro;
	}

	public Double getCostoGiro() {
		return this.costoGiro;
	}

	public void setCostoGiro(Double costoGiro) {
		this.costoGiro = costoGiro;
	}

	public String getIdDestino() {
		return this.idDestino;
	}

	public void setIdDestino(String idDestino) {
		this.idDestino = idDestino;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

	public String getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public String getIdVerificarMontoPermitido() {
		return this.idVerificarMontoPermitido;
	}

	public void setIdVerificarMontoPermitido(String idVerificarMontoPermitido) {
		this.idVerificarMontoPermitido = idVerificarMontoPermitido;
	}

	public String getIdVerficarMonto() {
		return this.idVerficarMonto;
	}

	public void setIdVerficarMonto(String idVerficarMonto) {
		this.idVerficarMonto = idVerficarMonto;
	}

}
