package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * LocutorioSedeEspana generated by hbm2java
 */
public class LocutorioSedeEspana implements java.io.Serializable {

	private String idLocutorio;
	private String idGiro;
	private String nombreLocutorio;
	private String emailLocutorio;
	private Long telefono;
	private String direccionLocutorio;
	private String idComprobanteRecepcionGiro;
	private String idGiros;
	private Set giroses = new HashSet(0);

	public LocutorioSedeEspana() {
	}

	public LocutorioSedeEspana(String idLocutorio) {
		this.idLocutorio = idLocutorio;
	}

	public LocutorioSedeEspana(String idLocutorio, String idGiro, String nombreLocutorio, String emailLocutorio,
			Long telefono, String direccionLocutorio, String idComprobanteRecepcionGiro, String idGiros, Set giroses) {
		this.idLocutorio = idLocutorio;
		this.idGiro = idGiro;
		this.nombreLocutorio = nombreLocutorio;
		this.emailLocutorio = emailLocutorio;
		this.telefono = telefono;
		this.direccionLocutorio = direccionLocutorio;
		this.idComprobanteRecepcionGiro = idComprobanteRecepcionGiro;
		this.idGiros = idGiros;
		this.giroses = giroses;
	}

	public String getIdLocutorio() {
		return this.idLocutorio;
	}

	public void setIdLocutorio(String idLocutorio) {
		this.idLocutorio = idLocutorio;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public String getNombreLocutorio() {
		return this.nombreLocutorio;
	}

	public void setNombreLocutorio(String nombreLocutorio) {
		this.nombreLocutorio = nombreLocutorio;
	}

	public String getEmailLocutorio() {
		return this.emailLocutorio;
	}

	public void setEmailLocutorio(String emailLocutorio) {
		this.emailLocutorio = emailLocutorio;
	}

	public Long getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Long telefono) {
		this.telefono = telefono;
	}

	public String getDireccionLocutorio() {
		return this.direccionLocutorio;
	}

	public void setDireccionLocutorio(String direccionLocutorio) {
		this.direccionLocutorio = direccionLocutorio;
	}

	public String getIdComprobanteRecepcionGiro() {
		return this.idComprobanteRecepcionGiro;
	}

	public void setIdComprobanteRecepcionGiro(String idComprobanteRecepcionGiro) {
		this.idComprobanteRecepcionGiro = idComprobanteRecepcionGiro;
	}

	public String getIdGiros() {
		return this.idGiros;
	}

	public void setIdGiros(String idGiros) {
		this.idGiros = idGiros;
	}

	public Set getGiroses() {
		return this.giroses;
	}

	public void setGiroses(Set giroses) {
		this.giroses = giroses;
	}

}
