package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * NegociacionFletes generated by hbm2java
 */
public class NegociacionFletes implements java.io.Serializable {

	private String idNegociacion;
	private BigInteger codNegociacion;
	private BigInteger comiBrokerQueEnvia;
	private BigInteger comiBanco;
	private BigInteger comiBrokerRecepcion;
	private BigInteger taxPaisEmisor;
	private Date fechaVigenciaInicial;
	private Date fechaVigenciaFinal;

	public NegociacionFletes() {
	}

	public NegociacionFletes(String idNegociacion) {
		this.idNegociacion = idNegociacion;
	}

	public NegociacionFletes(String idNegociacion, BigInteger codNegociacion, BigInteger comiBrokerQueEnvia,
			BigInteger comiBanco, BigInteger comiBrokerRecepcion, BigInteger taxPaisEmisor, Date fechaVigenciaInicial,
			Date fechaVigenciaFinal) {
		this.idNegociacion = idNegociacion;
		this.codNegociacion = codNegociacion;
		this.comiBrokerQueEnvia = comiBrokerQueEnvia;
		this.comiBanco = comiBanco;
		this.comiBrokerRecepcion = comiBrokerRecepcion;
		this.taxPaisEmisor = taxPaisEmisor;
		this.fechaVigenciaInicial = fechaVigenciaInicial;
		this.fechaVigenciaFinal = fechaVigenciaFinal;
	}

	public String getIdNegociacion() {
		return this.idNegociacion;
	}

	public void setIdNegociacion(String idNegociacion) {
		this.idNegociacion = idNegociacion;
	}

	public BigInteger getCodNegociacion() {
		return this.codNegociacion;
	}

	public void setCodNegociacion(BigInteger codNegociacion) {
		this.codNegociacion = codNegociacion;
	}

	public BigInteger getComiBrokerQueEnvia() {
		return this.comiBrokerQueEnvia;
	}

	public void setComiBrokerQueEnvia(BigInteger comiBrokerQueEnvia) {
		this.comiBrokerQueEnvia = comiBrokerQueEnvia;
	}

	public BigInteger getComiBanco() {
		return this.comiBanco;
	}

	public void setComiBanco(BigInteger comiBanco) {
		this.comiBanco = comiBanco;
	}

	public BigInteger getComiBrokerRecepcion() {
		return this.comiBrokerRecepcion;
	}

	public void setComiBrokerRecepcion(BigInteger comiBrokerRecepcion) {
		this.comiBrokerRecepcion = comiBrokerRecepcion;
	}

	public BigInteger getTaxPaisEmisor() {
		return this.taxPaisEmisor;
	}

	public void setTaxPaisEmisor(BigInteger taxPaisEmisor) {
		this.taxPaisEmisor = taxPaisEmisor;
	}

	public Date getFechaVigenciaInicial() {
		return this.fechaVigenciaInicial;
	}

	public void setFechaVigenciaInicial(Date fechaVigenciaInicial) {
		this.fechaVigenciaInicial = fechaVigenciaInicial;
	}

	public Date getFechaVigenciaFinal() {
		return this.fechaVigenciaFinal;
	}

	public void setFechaVigenciaFinal(Date fechaVigenciaFinal) {
		this.fechaVigenciaFinal = fechaVigenciaFinal;
	}

}
