package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String idPais;
	private String nombre;
	private String gentilicioNal;
	private String idNacionalidad;
	private Set clientes = new HashSet(0);

	public Pais() {
	}

	public Pais(String idPais) {
		this.idPais = idPais;
	}

	public Pais(String idPais, String nombre, String gentilicioNal, String idNacionalidad, Set clientes) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.gentilicioNal = gentilicioNal;
		this.idNacionalidad = idNacionalidad;
		this.clientes = clientes;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getGentilicioNal() {
		return this.gentilicioNal;
	}

	public void setGentilicioNal(String gentilicioNal) {
		this.gentilicioNal = gentilicioNal;
	}

	public String getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(String idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
