package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

/**
 * TipoClienteEstatica generated by hbm2java
 */
public class TipoClienteEstatica implements java.io.Serializable {

	private String idTipoCliente;
	private String nombre;

	public TipoClienteEstatica() {
	}

	public TipoClienteEstatica(String idTipoCliente) {
		this.idTipoCliente = idTipoCliente;
	}

	public TipoClienteEstatica(String idTipoCliente, String nombre) {
		this.idTipoCliente = idTipoCliente;
		this.nombre = nombre;
	}

	public String getIdTipoCliente() {
		return this.idTipoCliente;
	}

	public void setIdTipoCliente(String idTipoCliente) {
		this.idTipoCliente = idTipoCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
