package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * UbicacionCliente generated by hbm2java
 */
public class UbicacionCliente implements java.io.Serializable {

	private long idUbicacion;
	private Cliente cliente;
	private String nombre;
	private String direccionActual;
	private Long telefono;
	private String email;
	private Date fechaUltimoCamkbioResidencia;

	public UbicacionCliente() {
	}

	public UbicacionCliente(long idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	public UbicacionCliente(long idUbicacion, Cliente cliente, String nombre, String direccionActual, Long telefono,
			String email, Date fechaUltimoCamkbioResidencia) {
		this.idUbicacion = idUbicacion;
		this.cliente = cliente;
		this.nombre = nombre;
		this.direccionActual = direccionActual;
		this.telefono = telefono;
		this.email = email;
		this.fechaUltimoCamkbioResidencia = fechaUltimoCamkbioResidencia;
	}

	public long getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(long idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccionActual() {
		return this.direccionActual;
	}

	public void setDireccionActual(String direccionActual) {
		this.direccionActual = direccionActual;
	}

	public Long getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Long telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaUltimoCamkbioResidencia() {
		return this.fechaUltimoCamkbioResidencia;
	}

	public void setFechaUltimoCamkbioResidencia(Date fechaUltimoCamkbioResidencia) {
		this.fechaUltimoCamkbioResidencia = fechaUltimoCamkbioResidencia;
	}

}
