package co.edu.campusucc.sd.modelo;
// Generated 15-abr-2020 13:24:18 by Hibernate Tools 5.4.7.Final

/**
 * VerificacionMontoPermitido generated by hbm2java
 */
public class VerificacionMontoPermitido implements java.io.Serializable {

	private String idVerficarMonto;
	private String idCliente;
	private String idGiro;
	private String idGiros;
	private Boolean verficarMontoPermitido;
	private Double valorMontoPermitido;

	public VerificacionMontoPermitido() {
	}

	public VerificacionMontoPermitido(String idVerficarMonto, String idCliente) {
		this.idVerficarMonto = idVerficarMonto;
		this.idCliente = idCliente;
	}

	public VerificacionMontoPermitido(String idVerficarMonto, String idCliente, String idGiro, String idGiros,
			Boolean verficarMontoPermitido, Double valorMontoPermitido) {
		this.idVerficarMonto = idVerficarMonto;
		this.idCliente = idCliente;
		this.idGiro = idGiro;
		this.idGiros = idGiros;
		this.verficarMontoPermitido = verficarMontoPermitido;
		this.valorMontoPermitido = valorMontoPermitido;
	}

	public String getIdVerficarMonto() {
		return this.idVerficarMonto;
	}

	public void setIdVerficarMonto(String idVerficarMonto) {
		this.idVerficarMonto = idVerficarMonto;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public String getIdGiros() {
		return this.idGiros;
	}

	public void setIdGiros(String idGiros) {
		this.idGiros = idGiros;
	}

	public Boolean getVerficarMontoPermitido() {
		return this.verficarMontoPermitido;
	}

	public void setVerficarMontoPermitido(Boolean verficarMontoPermitido) {
		this.verficarMontoPermitido = verficarMontoPermitido;
	}

	public Double getValorMontoPermitido() {
		return this.valorMontoPermitido;
	}

	public void setValorMontoPermitido(Double valorMontoPermitido) {
		this.valorMontoPermitido = valorMontoPermitido;
	}

}
